package com.uottawa.seccharge.dataobjects;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BankAccount generated by hbm2java
 */
@Entity
@Table(name = "BANK_ACCOUNT")
public class BankAccount implements java.io.Serializable {

	private long id;
	private SecChargeUser secChargeUser;
	private long accountNum;
	private String bankName;
	private Date dateCreated;

	public BankAccount() {
	}

	public BankAccount(long id, SecChargeUser secChargeUser, long accountNum,
			String bankName, Date dateCreated) {
		this(secChargeUser, accountNum, bankName, dateCreated);
		this.id = id;
	}

	public BankAccount( SecChargeUser secChargeUser, long accountNum,
			String bankName, Date dateCreated) {
		this.secChargeUser = secChargeUser;
		this.accountNum = accountNum;
		this.bankName = bankName;
		this.dateCreated = dateCreated;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SECCHARGE_USERID", nullable = false)
	public SecChargeUser getSecChargeUser() {
		return this.secChargeUser;
	}

	public void setSecChargeUser(SecChargeUser secChargeUser) {
		this.secChargeUser = secChargeUser;
	}

	@Column(name = "ACCOUNTNUM", nullable = false, precision = 10, scale = 0)
	public long getAccountNum() {
		return this.accountNum;
	}

	public void setAccountNum(long accountNum) {
		this.accountNum = accountNum;
	}

	@Column(name = "BANKNAME", nullable = false, length = 40)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATECREATED", nullable = false, length = 7)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Override
	public String toString() {
		return "BankAccount [id=" + id + ", secChargeUser=" + secChargeUser + ", accountNum=" + accountNum + ", bankName="
				+ bankName + ", dateCreated=" + dateCreated + "]";
	}

}
