package com.uottawa.seccharge.dataobjects;
import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ChargingStation generated by hbm2java
 */
@Entity
@Table(name = "CHARGING_STATION", uniqueConstraints = @UniqueConstraint(columnNames = "SERIALNUMBER"))
public class ChargingStation implements Serializable {

	private Long id;
	private NetworkProvider networkProvider;
	private CsSite csSite;
	private String model;
	private Long csId;
	private String serialNumber;
	private Long longLocation;
	private Long latLocation;
	private String energyType;
	private Date pirceDate;
	private Long costKwh;
	private Set<ChargingLevel> chargingLevels = new HashSet<ChargingLevel>(0);
	private Set<SiteStatus> siteStatuses = new HashSet<SiteStatus>(0);

	public ChargingStation() {
	}

	public ChargingStation(NetworkProvider networkProvider,
			CsSite csSite, String model, String serialNumber,
			Long longLocation, Long latLocation,
			Date pirceDate, Long costKwh) {
		this.networkProvider = networkProvider;
		this.csSite = csSite;
		this.model = model;
		this.serialNumber = serialNumber;
		this.longLocation = longLocation;
		this.latLocation = latLocation;
		this.pirceDate = pirceDate;
		this.costKwh = costKwh;
	}
	
	public ChargingStation(Long id, NetworkProvider networkProvider,
			CsSite csSite, String model, String serialNumber,
			Long longLocation, Long latLocation,
			Date pirceDate, Long costKwh) {
		this(networkProvider, csSite, model, serialNumber, longLocation, latLocation, pirceDate, costKwh);
		this.id = id;
	}

	public ChargingStation(Long id, NetworkProvider networkProvider,
			CsSite csSite, String model, Long csId, String serialNumber,
			Long longLocation, Long latLocation, Date pirceDate, Long costKwh,
			Set<ChargingLevel> chargingLevels, Set<SiteStatus> siteStatuses) {
		this.id = id;
		this.networkProvider = networkProvider;
		this.csSite = csSite;
		this.model = model;
		this.csId = csId;
		this.serialNumber = serialNumber;
		this.longLocation = longLocation;
		this.latLocation = latLocation;
		this.chargingLevels = chargingLevels;
		this.siteStatuses = siteStatuses;
		this.pirceDate = pirceDate;
		this.costKwh = costKwh;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, precision = 32, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NETWORK_PROVIDERID", nullable = false)
	public NetworkProvider getNetworkProvider() {
		return this.networkProvider;
	}

	public void setNetworkProvider(NetworkProvider networkProvider) {
		this.networkProvider = networkProvider;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CS_SITEID", nullable = false)
	public CsSite getCsSite() {
		return this.csSite;
	}

	public void setCsSite(CsSite csSite) {
		this.csSite = csSite;
	}

	@Column(name = "MODEL", nullable = false)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "CS_ID", precision = 10, scale = 0)
	public Long getCsId() {
		return this.csId;
	}

	public void setCsId(Long csId) {
		this.csId = csId;
	}

	@Column(name = "SERIALNUMBER", unique = true, nullable = false)
	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	@Column(name = "LONGLOCATION", nullable = false, scale = 14)
	public Long getLongLocation() {
		return this.longLocation;
	}

	public void setLongLocation(Long longLocation) {
		this.longLocation = longLocation;
	}

	@Column(name = "LATLOCATION", nullable = false, scale = 14)
	public Long getLatLocation() {
		return this.latLocation;
	}

	public void setLatLocation(Long latLocation) {
		this.latLocation = latLocation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chargingStation", cascade = CascadeType.ALL)
	public Set<ChargingLevel> getChargingLevels() {
		return this.chargingLevels;
	}

	public void setChargingLevels(Set<ChargingLevel> chargingLevels) {
		this.chargingLevels = chargingLevels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chargingStation", cascade = CascadeType.ALL)
	public Set<SiteStatus> getSiteStatuses() {
		return this.siteStatuses;
	}

	public void setSiteStatuses(Set<SiteStatus> siteStatuses) {
		this.siteStatuses = siteStatuses;
	}
	@Column(name = "ENERGYTYPE", nullable = false, length = 10)
	public String getEnergyType() {
		return energyType;
	}

	public void setEnergyType(String energyType) {
		this.energyType = energyType;
		
		
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "PIRCEDATE", nullable = false, length = 7)
	public Date getPirceDate() {
		return this.pirceDate;
	}

	public void setPirceDate(Date pirceDate) {
		this.pirceDate = pirceDate;
	}

	@Column(name = "COSTKWH", nullable = false, precision = 10, scale = 10)
	public Long getCostKwh() {
		return this.costKwh;
	}

	public void setCostKwh(Long costKwh) {
		this.costKwh = costKwh;
	}

	@Override
	public String toString() {
		return "ChargingStation [id=" + id + ", networkProvider=" + networkProvider + ", csSite=" + csSite + ", model="
				+ model + ", csId=" + csId + ", serialNumber=" + serialNumber + ", longLocation=" + longLocation
				+ ", latLocation=" + latLocation + ", energyType=" + energyType + ", pirceDate=" + pirceDate + ", costKwh="
				+ costKwh + ", chargingLevels=" + chargingLevels + ", siteStatuses=" + siteStatuses + "]";
	}
}
