package com.uottawa.seccharge.dataobjects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChargingLevel generated by hbm2java
 */
@Entity
@Table(name = "CHARGING_LEVEL")
public class ChargingLevel implements java.io.Serializable {

	private int id;
	private ChargingStation chargingStation;
	private short portNumber;
	private String portLevel;
	private boolean status;

	public ChargingLevel() {
	}

	public ChargingLevel(int id, ChargingStation chargingStation,
			short portNumber, String portLevel, boolean status) {
		this(chargingStation, portNumber, portLevel, status);
		this.id = id;
	}
	
	public ChargingLevel(ChargingStation chargingStation,
			short portNumber, String portLevel, boolean status) {
		this.chargingStation = chargingStation;
		this.portNumber = portNumber;
		this.portLevel = portLevel;
		this.status = status;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, precision = 5, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CHARGING_STATIONID", nullable = false)
	public ChargingStation getChargingStation() {
		return this.chargingStation;
	}

	public void setChargingStation(ChargingStation chargingStation) {
		this.chargingStation = chargingStation;
	}

	@Column(name = "PORTNUMBER", nullable = false, precision = 3, scale = 0)
	public short getPortNumber() {
		return this.portNumber;
	}

	public void setPortNumber(short portNumber) {
		this.portNumber = portNumber;
	}
	@Column(name = "PORTLEVEL", nullable = false, length = 10)
	public String getPortLevel() {
		return this.portLevel;
	}

	public void setPortLevel(String portLevel) {
		this.portLevel = portLevel;
	}

	@Column(name = "STATUS", nullable = false, precision = 1, scale = 0)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Override
	public String toString() {
		return "ChargingLevel [id=" + id + ", chargingStation=" + chargingStation + ", portNumber=" + portNumber
				+ ", portLevel=" + portLevel + ", status=" + status + "]";
	}

}
