package com.uottawa.seccharge.dataobjects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "CITY")
public class City implements java.io.Serializable {

	private long id;
	private Province province;
	private String cityName;

	public City() {
	}

	public City(long id, Province province, String cityName) {
		this(province, cityName);
		this.id = id;
	}
	
	public City( Province province, String cityName) {
		this.province = province;
		this.cityName = cityName;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROVINCEID", nullable = false)
	public Province getProvince() {
		return this.province;
	}

	public void setProvince(Province province) {
		this.province = province;
	}

	@Column(name = "CITYNAME", nullable = false, length = 40)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@Override
	public String toString() {
		return "City [id=" + id + ", province=" + province + ", cityName=" + cityName + "]";
	}

	
}
