package com.uottawa.seccharge.dataobjects;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "COUNTRY")
public class Country implements java.io.Serializable {

	private int id;
	private String countryName;
	private Set<Province> provinces = new HashSet<Province>(0);

	public Country() {
	}

	public Country(int id, String countryName) {
		this.id = id;
		this.countryName = countryName;
	}

	public Country(String countryName) {
		this.countryName = countryName;
	}

	public Country(int id, String countryName, Set<Province> provinces) {
		this(countryName, provinces);
		this.id = id;
	}
	
	public Country(String countryName, Set<Province> provinces) {
		this.countryName = countryName;
		this.provinces = provinces;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, precision = 5, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Override
	public String toString() {
		return "Country [id=" + id + ", countryName=" + countryName + ", provinces=" + provinces + "]";
	}

	@Column(name = "COUNTRYNAME", nullable = false, length = 40)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country", cascade = CascadeType.ALL)
	public Set<Province> getProvinces() {
		return this.provinces;
	}

	public void setProvinces(Set<Province> provinces) {
		this.provinces = provinces;
	}

}
