package com.uottawa.seccharge.dataobjects;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * EnergySource generated by hbm2java
 */
@Entity
@Table(name = "ENERGY_SOURCE")
public class EnergySource implements Serializable {

	private int id;
	private String energySource;
	private String remarks;
	private Set<NetworkProvider> networkProviders = new HashSet<NetworkProvider>(0);

	public EnergySource() {
	}

	public EnergySource(int id, String remarks) {
		this.id = id;
		this.remarks = remarks;
	}

	public EnergySource(int id, String energySource, String remarks, Set<NetworkProvider> networkProviders) {
		this(energySource, remarks, networkProviders);
		this.id = id;
	}
	
	public EnergySource(String energySource, String remarks, Set<NetworkProvider> networkProviders) {
		this.energySource = energySource;
		this.remarks = remarks;
		this.networkProviders = networkProviders;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, precision = 5, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "ENERGYSOURCE", length = 60)
	public String getEnergySource() {
		return this.energySource;
	}

	public void setEnergySource(String energySource) {
		this.energySource = energySource;
	}

	@Column(name = "REMARKS", nullable = false, length = 510)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "ENERGYSOURCE_PROVIDER", joinColumns = { @JoinColumn(name = "ENERGYSOURCEID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "NETWORK_PROVIDERID", nullable = false, updatable = false) })
	public Set<NetworkProvider> getNetworkProviders() {
		return this.networkProviders;
	}

	public void setNetworkProviders(Set<NetworkProvider> networkProviders) {
		this.networkProviders = networkProviders;
	}

	@Override
	public String toString() {
		return "EnergySource [id=" + id + ", energySource=" + energySource + ", remarks=" + remarks + ", networkProviders="
				+ networkProviders + "]";
	}

}
