package com.uottawa.seccharge.dataobjects;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EvBattery generated by hbm2java
 */
@Entity
@Table(name = "EV_BATTERY")
public class EvBattery implements Serializable {

	private Long id;
	private ElectricalVehicle electricalVehicle;
	private String batteryType;
	private Long stateofCharge;

	public EvBattery() {
	}

	public EvBattery(Long id, ElectricalVehicle electricalVehicle, String batteryType, Long stateofCharge) {
		this(electricalVehicle, batteryType, stateofCharge);
		this.id = id;
	}
	
	public EvBattery(ElectricalVehicle electricalVehicle, String batteryType, Long stateofCharge) {
		this.electricalVehicle = electricalVehicle;
		this.batteryType = batteryType;
		this.stateofCharge = stateofCharge;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, precision = 32, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ELECTRICALVEHICLEID", nullable = false)
	public ElectricalVehicle getElectricalVehicle() {
		return this.electricalVehicle;
	}

	public void setElectricalVehicle(ElectricalVehicle electricalVehicle) {
		this.electricalVehicle = electricalVehicle;
	}

	@Column(name = "BATTERYTYPE", nullable = false, length = 50)
	public String getBatteryType() {
		return this.batteryType;
	}

	public void setBatteryType(String batteryType) {
		this.batteryType = batteryType;
	}

	@Column(name = "STATEOFCHARGE", nullable = false, precision = 5)
	public Long getStateofCharge() {
		return this.stateofCharge;
	}

	public void setStateofCharge(Long stateofCharge) {
		this.stateofCharge = stateofCharge;
	}

	@Override
	public String toString() {
		return "EvBattery [id=" + id + ", electricalVehicle=" + electricalVehicle + ", batteryType=" + batteryType
				+ ", stateofCharge=" + stateofCharge + "]";
	}
}
