package com.uottawa.seccharge.dataobjects;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EvCharging generated by hbm2java
 */
@Entity
@Table(name = "EV_CHARGING")
public class EvCharging implements Serializable {

	private Long id;
	private Transactions transactions;
	private Serializable startTime;
	private Serializable endTime;
	private Long chargingDuration;
	private Long consumptionKwh;

	public EvCharging() {
	}

	public EvCharging(Transactions transactions, Serializable startTime, Serializable endTime,
			Long chargingDuration, Long consumptionKwh) {
		this.transactions = transactions;
		this.startTime = startTime;
		this.endTime = endTime;
		this.chargingDuration = chargingDuration;
		this.consumptionKwh = consumptionKwh;
	}
	
	public EvCharging(Long id, Transactions transactions, Serializable startTime, Serializable endTime,
			Long chargingDuration, Long consumptionKwh) {
		this(transactions, startTime, endTime, chargingDuration, consumptionKwh);
		this.id = id;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, precision = 32, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRANSACTIONID", nullable = false)
	public Transactions getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Transactions transactions) {
		this.transactions = transactions;
	}

	@Column(name = "STARTTIME", nullable = false)
	public Serializable getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Serializable startTime) {
		this.startTime = startTime;
	}

	@Column(name = "ENDTIME", nullable = false)
	public Serializable getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Serializable endTime) {
		this.endTime = endTime;
	}

	@Column(name = "CHARGINGDURATION", nullable = false, precision = 10, scale = 10)
	public Long getChargingDuration() {
		return this.chargingDuration;
	}

	public void setChargingDuration(Long chargingDuration) {
		this.chargingDuration = chargingDuration;
	}

	@Column(name = "CONSUMPTIONKWH", nullable = false, precision = 10, scale = 10)
	public Long getConsumptionKwh() {
		return this.consumptionKwh;
	}

	public void setConsumptionKwh(Long consumptionKwh) {
		this.consumptionKwh = consumptionKwh;
	}

	@Override
	public String toString() {
		return "EvCharging [id=" + id + ", transactions=" + transactions + ", startTime=" + startTime + ", endTime="
				+ endTime + ", chargingDuration=" + chargingDuration + ", consumptionKwh=" + consumptionKwh + "]";
	}
}
