package com.uottawa.seccharge.dataobjects;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoginMonitor generated by hbm2java
 */
@Entity
@Table(name = "LOGIN_MONITOR")
public class LoginMonitor implements Serializable {

	private Long id;
	private SecChargeUser secChargeUser;
	private boolean clientType;
	private boolean success;
	private Date dateCreated;
	private Serializable timeCreated;
	private byte loginAttampts;

	public LoginMonitor() {
	}
	
	public LoginMonitor(SecChargeUser secChargeUser, boolean clientType, boolean success, Date dateCreated,
			Serializable timeCreated, byte loginAttampts) {
		this.secChargeUser = secChargeUser;
		this.clientType = clientType;
		this.success = success;
		this.dateCreated = dateCreated;
		this.timeCreated = timeCreated;
		this.loginAttampts = loginAttampts;
	}

	public LoginMonitor(Long id, SecChargeUser secChargeUser, boolean clientType, boolean success, Date dateCreated,
			Serializable timeCreated, byte loginAttampts) {
		this(secChargeUser, clientType, success, dateCreated, timeCreated, loginAttampts);
		this.id = id;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, precision = 32, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SECCHARGE_USERID", nullable = false)
	public SecChargeUser getSecChargeUser() {
		return this.secChargeUser;
	}

	public void setSecChargeUser(SecChargeUser secChargeUser) {
		this.secChargeUser = secChargeUser;
	}

	@Column(name = "CLIENTTYPE", nullable = false, precision = 1, scale = 0)
	public boolean isClientType() {
		return this.clientType;
	}

	public void setClientType(boolean clientType) {
		this.clientType = clientType;
	}

	@Column(name = "SUCCESS", nullable = false, precision = 1, scale = 0)
	public boolean isSuccess() {
		return this.success;
	}

	public void setSuccess(boolean success) {
		this.success = success;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATECREATED", nullable = false, length = 7)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "TIMECREATED", nullable = false)
	public Serializable getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(Serializable timeCreated) {
		this.timeCreated = timeCreated;
	}

	@Column(name = "LOGINATTAMPTS", nullable = false, precision = 2, scale = 0)
	public byte getLoginAttampts() {
		return this.loginAttampts;
	}

	public void setLoginAttampts(byte loginAttampts) {
		this.loginAttampts = loginAttampts;
	}

	@Override
	public String toString() {
		return "LoginMonitor [id=" + id + ", secChargeUser=" + secChargeUser + ", clientType=" + clientType + ", success="
				+ success + ", dateCreated=" + dateCreated + ", timeCreated=" + timeCreated + ", loginAttampts="
				+ loginAttampts + "]";
	}
}
