package com.uottawa.seccharge.dataobjects;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NetworkProvider generated by hbm2java
 */
@Entity
@Table(name = "NETWORK_PROVIDER")
public class NetworkProvider implements Serializable {

	private long id;
	private String providerName;
	private String address1;
	private String address2;
	private String city;
	private String province;
	private String postalCode;
	private String country;
	private String phone;
	private String tollfree;
	private String fax;
	private String emailContact;
	private String emailSupport;
	private Set<EnergySource> energySources = new HashSet<EnergySource>(0);
	private Set<ChargingStation> chargingStations = new HashSet<ChargingStation>(0);
	private Set<PaymentsHistory> paymentsHistories = new HashSet<PaymentsHistory>(0);

	public NetworkProvider() {
	}

	public NetworkProvider(String providerName, String address1, String city, String province, String postalCode,
			String country, String emailContact) {
		this.providerName = providerName;
		this.address1 = address1;
		this.city = city;
		this.province = province;
		this.postalCode = postalCode;
		this.country = country;
		this.emailContact = emailContact;
	}

	public NetworkProvider(long id, String providerName, String address1, String city, String province, String postalCode,
			String country, String emailContact) {
		this(providerName, address1, city, province, postalCode, country, emailContact);
		this.id = id;
	}

	public NetworkProvider(String providerName, String address1, String address2, String city, String province,
			String postalCode, String country, String phone, String tollfree, String fax, String emailContact,
			String emailSupport, Set<EnergySource> energySources, Set<ChargingStation> chargingStations,
			Set<PaymentsHistory> paymentsHistories) {
		this(providerName, address1, city, province, postalCode, country, emailContact);
		this.address2 = address2;
		this.phone = phone;
		this.tollfree = tollfree;
		this.fax = fax;
		this.emailSupport = emailSupport;
		this.energySources = energySources;
		this.chargingStations = chargingStations;
		this.paymentsHistories = paymentsHistories;
	}

	public NetworkProvider(long id, String providerName, String address1, String address2, String city, String province,
			String postalCode, String country, String phone, String tollfree, String fax, String emailContact,
			String emailSupport, Set<EnergySource> energySources, Set<ChargingStation> chargingStations,
			Set<PaymentsHistory> paymentsHistories) {
		this(providerName, address1, address2, city, province, postalCode, country, phone, tollfree, fax, emailContact,
				emailSupport, energySources, chargingStations, paymentsHistories);
		this.id = id;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "PROVIDERNAME", nullable = false, length = 40)
	public String getProvidername() {
		return this.providerName;
	}

	public void setProvidername(String providerName) {
		this.providerName = providerName;
	}

	@Column(name = "ADDRESS1", nullable = false)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "ADDRESS2")
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "CITY", nullable = false, length = 40)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "PROVINCE", nullable = false, length = 40)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "POSTALCODE", nullable = false, length = 10)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "COUNTRY", nullable = false, length = 40)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "PHONE", length = 10)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "TOLLFREE", length = 10)
	public String getTollfree() {
		return this.tollfree;
	}

	public void setTollfree(String tollfree) {
		this.tollfree = tollfree;
	}

	@Column(name = "FAX", length = 10)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "EMAILCONTACT", nullable = false, length = 80)
	public String getEmailContact() {
		return this.emailContact;
	}

	public void setEmailContact(String emailContact) {
		this.emailContact = emailContact;
	}

	@Column(name = "EMAILSUPPORT", length = 40)
	public String getEmailSupport() {
		return this.emailSupport;
	}

	public void setEmailSupport(String emailSupport) {
		this.emailSupport = emailSupport;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "ENERGYSOURCE_PROVIDER", joinColumns = { @JoinColumn(name = "NETWORK_PROVIDERID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "ENERGYSOURCEID", nullable = false, updatable = false) })
	public Set<EnergySource> getEnergySources() {
		return this.energySources;
	}

	public void setEnergySources(Set<EnergySource> energySources) {
		this.energySources = energySources;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "networkProvider", cascade = CascadeType.ALL)
	public Set<ChargingStation> getChargingStations() {
		return this.chargingStations;
	}

	public void setChargingStations(Set<ChargingStation> chargingStations) {
		this.chargingStations = chargingStations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "networkProvider", cascade = CascadeType.ALL)
	public Set<PaymentsHistory> getPaymentsHistories() {
		return this.paymentsHistories;
	}

	public void setPaymentsHistories(Set<PaymentsHistory> paymentsHistories) {
		this.paymentsHistories = paymentsHistories;
	}

	@Override
	public String toString() {
		return "NetworkProvider [id=" + id + ", providerName=" + providerName + ", address1=" + address1 + ", address2="
				+ address2 + ", city=" + city + ", province=" + province + ", postalCode=" + postalCode + ", country="
				+ country + ", phone=" + phone + ", tollfree=" + tollfree + ", fax=" + fax + ", emailContact="
				+ emailContact + ", emailSupport=" + emailSupport + ", energySources=" + energySources
				+ ", chargingStations=" + chargingStations + ", paymentsHistories=" + paymentsHistories + "]";
	}
}
