package com.uottawa.seccharge.dataobjects;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PaymentsHistory generated by hbm2java
 */
@Entity
@Table(name = "PAYMENTS_HISTORY", uniqueConstraints = @UniqueConstraint(columnNames = "PYMENTID"))
public class PaymentsHistory implements Serializable {

	private Long id;
	private NetworkProvider networkProvider;
	private SecChargeUser secChargeUser;
	private String pymentId;
	private Date paymentDate;
	private boolean paid;
	private Long amountPaid;
	private String pymentMethod;
	private String invoiceNumber;

	public PaymentsHistory() {
	}

	public PaymentsHistory(NetworkProvider networkProvider, SecChargeUser secChargeUser, String pymentId, Date paymentDate,
			boolean paid, Long amountPaid, String pymentMethod, String invoiceNumber) {
		this.networkProvider = networkProvider;
		this.secChargeUser = secChargeUser;
		this.pymentId = pymentId;
		this.paymentDate = paymentDate;
		this.paid = paid;
		this.amountPaid = amountPaid;
		this.pymentMethod = pymentMethod;
		this.invoiceNumber = invoiceNumber;
	}

	public PaymentsHistory(Long id, NetworkProvider networkProvider, SecChargeUser secChargeUser, String pymentId,
			Date paymentDate, boolean paid, Long amountPaid, String pymentMethod, String invoiceNumber) {
		this(networkProvider, secChargeUser, pymentId, paymentDate, paid, amountPaid, pymentMethod, invoiceNumber);
		this.id = id;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, precision = 32, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CS_NETWORK_PROVIDERID", nullable = false)
	public NetworkProvider getNetworkProvider() {
		return this.networkProvider;
	}

	public void setNetworkProvider(NetworkProvider networkProvider) {
		this.networkProvider = networkProvider;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SECCHARGE_USERID", nullable = false)
	public SecChargeUser getSecChargeUser() {
		return this.secChargeUser;
	}

	public void setSecChargeUser(SecChargeUser secChargeUser) {
		this.secChargeUser = secChargeUser;
	}

	@Column(name = "PYMENTID", unique = true, nullable = false, length = 40)
	public String getPymentId() {
		return this.pymentId;
	}

	public void setPymentId(String pymentId) {
		this.pymentId = pymentId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PAYMENTDATE", nullable = false, length = 7)
	public Date getPaymentdate() {
		return this.paymentDate;
	}

	public void setPaymentdate(Date paymentDate) {
		this.paymentDate = paymentDate;
	}

	@Column(name = "PAID", nullable = false, precision = 1, scale = 0)
	public boolean isPaid() {
		return this.paid;
	}

	public void setPaid(boolean paid) {
		this.paid = paid;
	}

	@Column(name = "AMOUNTPAID", nullable = false, precision = 10, scale = 10)
	public Long getAmountPaid() {
		return this.amountPaid;
	}

	public void setAmountPaid(Long amountPaid) {
		this.amountPaid = amountPaid;
	}

	@Column(name = "PYMENTMETHOD", nullable = false, length = 40)
	public String getPymentMethod() {
		return this.pymentMethod;
	}

	public void setPymentMethod(String pymentMethod) {
		this.pymentMethod = pymentMethod;
	}

	@Column(name = "INVOICENUMBER", nullable = false, length = 40)
	public String getInvoiceNumber() {
		return this.invoiceNumber;
	}

	public void setInvoiceNumber(String invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	@Override
	public String toString() {
		return "PaymentsHistory [id=" + id + ", networkProvider=" + networkProvider + ", secChargeUser=" + secChargeUser
				+ ", pymentId=" + pymentId + ", paymentDate=" + paymentDate + ", paid=" + paid + ", amountPaid="
				+ amountPaid + ", pymentMethod=" + pymentMethod + ", invoiceNumber=" + invoiceNumber + "]";
	}
}
