package com.uottawa.seccharge.dataobjects;

// Generated 1-Dec-2014 5:23:19 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AllPermissions generated by hbm2java
 */
@Entity
@Table(name = "ALL_PERMISSIONS")
public class Permission implements Serializable {

	private long id;
	private String permissionName;
	private Set<PermissionRoles> permissionRoles = new HashSet<PermissionRoles>(0);

	public Permission() {
	}

	public Permission(long id, String permissionName) {
		this.id = id;
		this.permissionName = permissionName;
	}

	public Permission(long id, String permissionName, Set<PermissionRoles> permissionRoles) {
		this(permissionName, permissionRoles);
		this.id = id;
	}

	public Permission(String permissionName, Set<PermissionRoles> permissionRoles) {
		this.permissionName = permissionName;
		this.permissionRoles = permissionRoles;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "PERMISSIONNAME", nullable = false, length = 40)
	public String getPermissionName() {
		return this.permissionName;
	}

	public void setPermissionName(String permissionName) {
		this.permissionName = permissionName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "allPermissions", cascade = CascadeType.ALL)
	public Set<PermissionRoles> getPermissionRoles() {
		return this.permissionRoles;
	}

	public void setPermissionRoles(Set<PermissionRoles> permissionRoles) {
		this.permissionRoles = permissionRoles;
	}

	@Override
	public String toString() {
		return "AllPermissions [id=" + id + ", permissionName=" + permissionName + ", permissionRoles=" + permissionRoles
				+ "]";
	}

}
