package com.uottawa.seccharge.dataobjects;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PermissionRoles generated by hbm2java
 */
@Entity
@Table(name = "PERMISSION_ROLES")
public class PermissionRoles implements Serializable {

	private PermissionRolesId id;
	private Role allRoles;
	private Permission allPermissions;
	private Date dateCreated;

	public PermissionRoles() {
	}

	public PermissionRoles(Role allRoles, Permission allPermissions) {
		this.allRoles = allRoles;
		this.allPermissions = allPermissions;
	}
	
	public PermissionRoles(PermissionRolesId id, Role allRoles, Permission allPermissions) {
		this(allRoles, allPermissions);
		this.id = id;
	}

	public PermissionRoles(PermissionRolesId id, Role allRoles, Permission allPermissions, Date dateCreated) {
		this(allRoles, allPermissions, dateCreated);
		this.id = id;
	}
	
	public PermissionRoles(Role allRoles, Permission allPermissions, Date dateCreated) {
		this.allRoles = allRoles;
		this.allPermissions = allPermissions;
		this.dateCreated = dateCreated;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "permissionid", column = @Column(name = "PERMISSIONID", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "rolesid", column = @Column(name = "ROLESID", nullable = false, precision = 10, scale = 0)) })
	public PermissionRolesId getId() {
		return this.id;
	}

	public void setId(PermissionRolesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLESID", nullable = false, insertable = false, updatable = false)
	public Role getAllRoles() {
		return this.allRoles;
	}

	public void setAllRoles(Role allRoles) {
		this.allRoles = allRoles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERMISSIONID", nullable = false, insertable = false, updatable = false)
	public Permission getAllPermissions() {
		return this.allPermissions;
	}

	public void setAllPermissions(Permission allPermissions) {
		this.allPermissions = allPermissions;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATECREATED", length = 7)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Override
	public String toString() {
		return "PermissionRoles [id=" + id + ", allRoles=" + allRoles + ", allPermissions=" + allPermissions
				+ ", dateCreated=" + dateCreated + "]";
	}
	
}
