package com.uottawa.seccharge.dataobjects;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PermissionRolesId generated by hbm2java
 */
@Embeddable
public class PermissionRolesId implements Serializable {

	private long permissionId;
	private long rolesId;

	public PermissionRolesId() {
	}

	public PermissionRolesId(long permissionId, long rolesId) {
		this.permissionId = permissionId;
		this.rolesId = rolesId;
	}

	@Column(name = "PERMISSIONID", nullable = false, precision = 10, scale = 0)
	public long getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(long permissionId) {
		this.permissionId = permissionId;
	}

	@Column(name = "ROLESID", nullable = false, precision = 10, scale = 0)
	public long getRolesId() {
		return this.rolesId;
	}

	public void setRolesId(long rolesId) {
		this.rolesId = rolesId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PermissionRolesId))
			return false;
		PermissionRolesId castOther = (PermissionRolesId) other;

		return (this.getPermissionId() == castOther.getPermissionId()) && (this.getRolesId() == castOther.getRolesId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPermissionId();
		result = 37 * result + (int) this.getRolesId();
		return result;
	}

}
