package com.uottawa.seccharge.dataobjects;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name = "RESERVATION")
public class Reservation implements Serializable {

	private Long id;
	private SecChargeUser secChargeUser;
	private Date timeCreated;
	private boolean active;
	private Date timeCancelation;
	private Set<SiteReservation> siteReservations = new HashSet<SiteReservation>(0);

	public Reservation() {
	}
	
	public Reservation(SecChargeUser secChargeUser, Date timeCreated, boolean active) {
		this.secChargeUser = secChargeUser;
		this.timeCreated = timeCreated;
		this.active = active;
	}

	public Reservation(Long id, SecChargeUser secChargeUser, Date timeCreated,
			boolean active) {
		this(secChargeUser, timeCreated, active);
		this.id = id;
	}

	public Reservation(SecChargeUser secChargeUser, Date timeCreated, boolean active,
			Date timeCancelation, Set<SiteReservation> siteReservations) {
		this.secChargeUser = secChargeUser;
		this.timeCreated = timeCreated;
		this.active = active;
		this.timeCancelation = timeCancelation;
		this.siteReservations = siteReservations;
	}
	
	public Reservation(Long id, SecChargeUser secChargeUser,Date timeCreated,
			boolean active,
			Date timeCancelation, Set<SiteReservation> siteReservations) {
		this(secChargeUser, timeCreated, active, timeCancelation, siteReservations);
		this.id = id;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, precision = 32, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SECCHARGE_USERID", nullable = false)
	public SecChargeUser getSecChargeUser() {
		return this.secChargeUser;
	}

	public void setSecChargeUser(SecChargeUser secChargeUser) {
		this.secChargeUser = secChargeUser;
	}

	@Column(name = "TIMECREATED", nullable = false)
	public Date getTimeCreated() {
		return this.timeCreated;
	}

	public void setTimeCreated(Date timeCreated) {
		this.timeCreated = timeCreated;
	}

	@Column(name = "ACTIVE", nullable = false, precision = 1, scale = 0)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "TIMECANCELATION")
	public Date getTimeCancelation() {
		return this.timeCancelation;
	}

	public void setTimeCancelation(Date timeCancelation) {
		this.timeCancelation = timeCancelation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reservation", cascade = CascadeType.ALL)
	public Set<SiteReservation> getSiteReservations() {
		return this.siteReservations;
	}

	public void setSiteReservations(Set<SiteReservation> siteReservations) {
		this.siteReservations = siteReservations;
	}

	@Override
	public String toString() {
		return "Reservation [id=" + id + ", secChargeUser=" + secChargeUser + ", timeCreated=" + timeCreated + ", active="
				+ active + ", timeCancelation=" + timeCancelation + ", siteReservations=" + siteReservations + "]";
	}

}
