package com.uottawa.seccharge.dataobjects;

// Generated 1-Dec-2014 5:23:19 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AllRoles generated by hbm2java
 */
@Entity
@Table(name = "ALL_ROLES")
public class Role implements Serializable {

	private long id;
	private String roleName;
	private Set<SecChargeuserRoles> secchargeuserRoles = new HashSet<SecChargeuserRoles>(0);
	private Set<PermissionRoles> permissionRoles = new HashSet<PermissionRoles>(0);

	public Role() {
	}

	public Role(long id, String roleName) {
		this.id = id;
		this.roleName = roleName;
	}

	public Role(String roleName) {
		this.roleName = roleName;
	}

	public Role(long id, String roleName, Set<SecChargeuserRoles> secchargeuserRoles, Set<PermissionRoles> permissionRoles) {
		this(roleName, secchargeuserRoles, permissionRoles);
		this.id = id;
	}

	public Role(String roleName, Set<SecChargeuserRoles> secchargeuserRoles, Set<PermissionRoles> permissionRoles) {
		this.roleName = roleName;
		this.secchargeuserRoles = secchargeuserRoles;
		this.permissionRoles = permissionRoles;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "ROLENAME", nullable = false, length = 40)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "allRoles", cascade = CascadeType.ALL)
	public Set<SecChargeuserRoles> getSecchargeuserRoleses() {
		return this.secchargeuserRoles;
	}

	public void setSecchargeuserRoleses(Set<SecChargeuserRoles> secchargeuserRoles) {
		this.secchargeuserRoles = secchargeuserRoles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "allRoles", cascade = CascadeType.ALL)
	public Set<PermissionRoles> getPermissionRoleses() {
		return this.permissionRoles;
	}

	public void setPermissionRoleses(Set<PermissionRoles> permissionRoles) {
		this.permissionRoles = permissionRoles;
	}

	@Override
	public String toString() {
		return "Role [id=" + id + ", roleName=" + roleName + ", secchargeuserRoles=" + secchargeuserRoles
				+ ", permissionRoles=" + permissionRoles + "]";
	}

}
