package com.uottawa.seccharge.dataobjects;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SecchargeUser generated by hbm2java
 */
@Entity
@Table(name = "SECCHARGE_USER", uniqueConstraints = {
		@UniqueConstraint(columnNames = "USERSALT"),
		@UniqueConstraint(columnNames = "USERNAME") })
public class SecChargeUser implements java.io.Serializable {

	private Long id;
	private String userName;
	private String password;
	private String usersalt;
	private boolean active;
	private boolean locked;
	private Set<LoginMonitor> loginMonitors = new HashSet<LoginMonitor>(0);
	//private Set<UserMetadata> userMetadata = new HashSet<UserMetadata>(0);
	private UserMetadata userMetadata;
	private Set<SecChargeQuestions> secChargeQuestions = new HashSet<SecChargeQuestions>(
			0);
	
	private Set<Transactions> transactionses = new HashSet<Transactions>(0);
	private Set<Reservation> reservations = new HashSet<Reservation>(0);
	private Set<BankAccount> bankAccounts = new HashSet<BankAccount>(0);
	private Set<UserMetadataEv> userMetadataEvs = new HashSet<UserMetadataEv>(0);
	private Set<SecChargeuserRoles> secchargeuserRoles = new HashSet<SecChargeuserRoles>(
			0);
	private Set<PaymentsHistory> paymentsHistories = new HashSet<PaymentsHistory>(
			0);
	private Set<ThirdprtyBilling> thirdprtyBillings = new HashSet<ThirdprtyBilling>(
			0);
	private Set<TransactionHistroy> transactionHistroys = new HashSet<TransactionHistroy>(
			0);


	public SecChargeUser() {
	}

	public SecChargeUser(Long id, String userName, String password,
			String usersalt, boolean active, boolean locked) {
		this.id = id;
		this.userName = userName;
		this.password = password;
		this.usersalt = usersalt;
		this.active = active;
		this.locked = locked;
	}

	public SecChargeUser(String userName, String password,
			String usersalt, boolean active, boolean locked) {
		this.userName = userName;
		this.password = password;
		this.usersalt = usersalt;
		this.active = active;
		this.locked = locked;
	}
	
	public SecChargeUser(Long id, String userName, String password,
			boolean active, boolean locked,
			Set<LoginMonitor> loginMonitors, UserMetadata userMetadata,
			Set<SecChargeQuestions> secChargeQuestionses) {
		this.id = id;
		this.userName = userName;
		this.password = password;
		this.active = active;
		this.locked = locked;
		this.loginMonitors = loginMonitors;
		this.userMetadata = userMetadata;
		this.secChargeQuestions = secChargeQuestionses;
	}

	public SecChargeUser( String userName, String password,
			boolean active, boolean locked,
			Set<LoginMonitor> loginMonitors, UserMetadata userMetadata,
			Set<SecChargeQuestions> secChargeQuestionses,Set<Transactions> transactionses, Set<Reservation> reservations,
			Set<BankAccount> bankAccounts, Set<UserMetadataEv> userMetadataEvs,
			Set<SecChargeuserRoles> secchargeuserRoleses,
			Set<PaymentsHistory> paymentsHistories,
			Set<ThirdprtyBilling> thirdprtyBillings,
			Set<TransactionHistroy> transactionHistroys) {
		this.userName = userName;
		this.password = password;
		this.active = active;
		this.locked = locked;
		this.loginMonitors = loginMonitors;
		this.userMetadata = userMetadata;
		this.secChargeQuestions = secChargeQuestionses;
		this.transactionses = transactionses;
		this.reservations = reservations;
		this.bankAccounts = bankAccounts;
		this.userMetadataEvs = userMetadataEvs;
		this.secchargeuserRoles = secchargeuserRoleses;
		this.paymentsHistories = paymentsHistories;
		this.thirdprtyBillings = thirdprtyBillings;
		this.transactionHistroys = transactionHistroys;
	}
	
	public SecChargeUser( String userName, String password,
			boolean active, boolean locked,
			 UserMetadata userMetadata) {
		this.userName = userName;
		this.password = password;
		this.active = active;
		this.locked = locked;
		this.userMetadata = userMetadata;
	}
	
	@Id @GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, precision = 32, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "USERNAME", unique = true, nullable = false, length = 80)
	public String getUsername() {
		return this.userName;
	}

	public void setUsername(String userName) {
		this.userName = userName;
	}

	@Column(name = "PASSWORD", nullable = false, length = 128)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "USERSALT", unique = true, nullable = false, length = 80)
	public String getUsersalt() {
		return this.usersalt;
	}

	public void setUsersalt(String usersalt) {
		this.usersalt = usersalt;
	}
		

	@Column(name = "ACTIVE", nullable = false, precision = 1, scale = 0)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "LOCKED", nullable = false, precision = 1, scale = 0)
	public boolean isLocked() {
		return this.locked;
	}

	public void setLocked(boolean locked) {
		this.locked = locked;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "secChargeUser", cascade = CascadeType.ALL)
	public Set<LoginMonitor> getLoginMonitors() {
		return this.loginMonitors;
	}

	public void setLoginMonitors(Set<LoginMonitor> loginMonitors) {
		this.loginMonitors = loginMonitors;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "secChargeUser", cascade = CascadeType.ALL)
	public UserMetadata getUserMetadata() {
		return this.userMetadata;
	}

	public void setUserMetadata(UserMetadata userMetadata) {
		this.userMetadata = userMetadata;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "secChargeUser",cascade=CascadeType.ALL)
	public Set<SecChargeQuestions> getSecChargeQuestions() {
		return this.secChargeQuestions;
	}

	public void setSecChargeQuestions(
			Set<SecChargeQuestions> secChargeQuestions) {
		this.secChargeQuestions = secChargeQuestions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "secChargeUser",cascade=CascadeType.ALL)
	public Set<Transactions> getTransactionses() {
		return this.transactionses;
	}

	public void setTransactionses(Set<Transactions> transactionses) {
		this.transactionses = transactionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "secChargeUser",cascade=CascadeType.ALL)
	public Set<Reservation> getReservations() {
		return this.reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "secChargeUser",cascade=CascadeType.ALL)
	public Set<BankAccount> getBankAccounts() {
		return this.bankAccounts;
	}

	public void setBankAccounts(Set<BankAccount> bankAccounts) {
		this.bankAccounts = bankAccounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "secChargeUser",cascade=CascadeType.ALL)
	public Set<UserMetadataEv> getUserMetadataEvs() {
		return this.userMetadataEvs;
	}

	public void setUserMetadataEvs(Set<UserMetadataEv> userMetadataEvs) {
		this.userMetadataEvs = userMetadataEvs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "secChargeUser",cascade=CascadeType.ALL)
	public Set<SecChargeuserRoles> getSecchargeuserRoles() {
		return this.secchargeuserRoles;
	}

	public void setSecchargeuserRoles(
			Set<SecChargeuserRoles> secchargeuserRoles) {
		this.secchargeuserRoles = secchargeuserRoles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "secChargeUser",cascade=CascadeType.ALL)
	public Set<PaymentsHistory> getPaymentsHistories() {
		return this.paymentsHistories;
	}

	public void setPaymentsHistories(Set<PaymentsHistory> paymentsHistories) {
		this.paymentsHistories = paymentsHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "secChargeUser",cascade=CascadeType.ALL)
	public Set<ThirdprtyBilling> getThirdprtyBillings() {
		return this.thirdprtyBillings;
	}

	public void setThirdprtyBillings(Set<ThirdprtyBilling> thirdprtyBillings) {
		this.thirdprtyBillings = thirdprtyBillings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "secChargeUser",cascade=CascadeType.ALL)
	public Set<TransactionHistroy> getTransactionHistroys() {
		return this.transactionHistroys;
	}

	public void setTransactionHistroys(
			Set<TransactionHistroy> transactionHistroys) {
		this.transactionHistroys = transactionHistroys;
	}

	@Override
	public String toString() {
		return "SecChargeUser [id=" + id + ", userName=" + userName
				+ ", password=" + password 
				+", active=" + active + ", locked=" + locked + "]";
	}

}
