package com.uottawa.seccharge.dataobjects;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SecchargeuserRolesId generated by hbm2java
 */
@Embeddable
public class SecChargeuserRolesId implements Serializable {

	private long rolesId;
	private Long userMetadataid;

	public SecChargeuserRolesId() {
	}

	public SecChargeuserRolesId(long rolesId, Long userMetadataid) {
		this.rolesId = rolesId;
		this.userMetadataid = userMetadataid;
	}

	@Column(name = "ROLESID", nullable = false, precision = 10, scale = 0)
	public long getRolesId() {
		return this.rolesId;
	}

	public void setRolesId(long rolesId) {
		this.rolesId = rolesId;
	}

	@Column(name = "USER_METADATAID", nullable = false, precision = 32, scale = 0)
	public Long getUserMetadataid() {
		return this.userMetadataid;
	}

	public void setUserMetadataid(Long userMetadataid) {
		this.userMetadataid = userMetadataid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SecChargeuserRolesId))
			return false;
		SecChargeuserRolesId castOther = (SecChargeuserRolesId) other;

		return (this.getRolesId() == castOther.getRolesId())
				&& ((this.getUserMetadataid() == castOther.getUserMetadataid()) || (this.getUserMetadataid() != null
						&& castOther.getUserMetadataid() != null && this.getUserMetadataid().equals(
						castOther.getUserMetadataid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRolesId();
		result = 37 * result + (getUserMetadataid() == null ? 0 : this.getUserMetadataid().hashCode());
		return result;
	}

	@Override
	public String toString() {
		return "SecChargeuserRolesId [rolesId=" + rolesId + ", userMetadataid=" + userMetadataid + "]";
	}

}
