package com.uottawa.seccharge.dataobjects;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SecchargeuserRoles generated by hbm2java
 */
@Entity
@Table(name = "SECCHARGEUSER_ROLES")
public class SecChargeuserRoles implements Serializable {

	private SecChargeuserRolesId id;
	private Role allRoles;
	private SecChargeUser secChargeUser;
	private Date dateCreated;
	private Date dateBegin;
	private Date endDate;

	public SecChargeuserRoles() {
	}

	public SecChargeuserRoles(Role allRoles, SecChargeUser secChargeUser, Date dateCreated,
			Date dateBegin) {
		this.allRoles = allRoles;
		this.secChargeUser = secChargeUser;
		this.dateCreated = dateCreated;
		this.dateBegin = dateBegin;
	}
	
	public SecChargeuserRoles(SecChargeuserRolesId id, Role allRoles, SecChargeUser secChargeUser, Date dateCreated,
			Date dateBegin) {
		this(allRoles, secChargeUser, dateCreated, dateBegin);
		this.id = id;
	}

	public SecChargeuserRoles(SecChargeuserRolesId id, Role allRoles, SecChargeUser secChargeUser, Date dateCreated,
			Date dateBegin, Date endDate) {
		this(allRoles, secChargeUser, dateCreated, dateBegin, endDate);
		this.id = id;
	}
	
	public SecChargeuserRoles(Role allRoles, SecChargeUser secChargeUser, Date dateCreated,
			Date dateBegin, Date endDate) {
		this(allRoles, secChargeUser, dateCreated, dateBegin);
		this.endDate = endDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "rolesid", column = @Column(name = "ROLESID", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "userMetadataid", column = @Column(name = "USER_METADATAID", nullable = false, precision = 32, scale = 0)) })
	public SecChargeuserRolesId getId() {
		return this.id;
	}

	public void setId(SecChargeuserRolesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLESID", nullable = false, insertable = false, updatable = false)
	public Role getAllRoles() {
		return this.allRoles;
	}

	public void setAllRoles(Role allRoles) {
		this.allRoles = allRoles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SECCHARGE_USERID", nullable = false, insertable = false, updatable = false)
	public SecChargeUser getSecChargeUser() {
		return this.secChargeUser;
	}

	public void setSecChargeUser(SecChargeUser SecChargeUser) {
		this.secChargeUser = secChargeUser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATECREATED", nullable = false, length = 7)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEBEGIN", nullable = false, length = 7)
	public Date getDateBegin() {
		return this.dateBegin;
	}

	public void setDateBegin(Date dateBegin) {
		this.dateBegin = dateBegin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ENDDATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Override
	public String toString() {
		return "SecChargeuserRoles [id=" + id + ", allRoles=" + allRoles + ", secChargeUser=" + secChargeUser
				+ ", dateCreated=" + dateCreated + ", dateBegin=" + dateBegin + ", endDate=" + endDate + "]";
	}

}
