package com.uottawa.seccharge.dataobjects;

import java.io.Serializable;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SecchargeQuestions generated by hbm2java
 */
@Entity
@Table(name = "SECCHARGE_QUESTIONS")
public class SecChargeQuestions implements Serializable {

	private SecchargeQuestionsId id;
	private SecChargeUser secChargeUser;
	private SecurityQuestions securityQuestions;
	private String answer;

	public SecChargeQuestions() {
	}
	
	public SecChargeQuestions(SecChargeUser secChargeUser, SecurityQuestions securityQuestions,
			String answer) {
		this.secChargeUser = secChargeUser;
		this.securityQuestions = securityQuestions;
		this.answer = answer;
	}

	public SecChargeQuestions(SecchargeQuestionsId id, SecChargeUser secChargeUser, SecurityQuestions securityQuestions,
			String answer) {
		this(secChargeUser, securityQuestions, answer);
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "secChargeUserid", column = @Column(name = "SECCHARGE_USERID", nullable = false, precision = 32, scale = 0)),
			@AttributeOverride(name = "securityQuestionsid", column = @Column(name = "SECURITY_QUESTIONSID", nullable = false, precision = 5, scale = 0)) })
	public SecchargeQuestionsId getId() {
		return this.id;
	}

	public void setId(SecchargeQuestionsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SECCHARGE_USERID", nullable = false, insertable = false, updatable = false)
	public SecChargeUser getSecChargeUser() {
		return this.secChargeUser;
	}

	public void setSecChargeUser(SecChargeUser secChargeUser) {
		this.secChargeUser = secChargeUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SECURITY_QUESTIONSID", nullable = false, insertable = false, updatable = false)
	public SecurityQuestions getSecurityQuestions() {
		return this.securityQuestions;
	}

	public void setSecurityQuestions(SecurityQuestions securityQuestions) {
		this.securityQuestions = securityQuestions;
	}

	@Column(name = "ANSWER", nullable = false, length = 200)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	@Override
	public String toString() {
		return "SecChargeQuestions [id=" + id + ", secChargeUser=" + secChargeUser + ", securityQuestions="
				+ securityQuestions + ", answer=" + answer + "]";
	}

}
