package com.uottawa.seccharge.dataobjects;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SecurityQuestions generated by hbm2java
 */
@Entity
@Table(name = "SECURITY_QUESTIONS")
public class SecurityQuestions implements Serializable {

	private int id;
	private String securityQuestion;
	private Set<SecChargeQuestions> secChargeQuestions = new HashSet<SecChargeQuestions>(0);

	public SecurityQuestions() {
	}
	
	public SecurityQuestions(String securityQuestion) {
		this.securityQuestion = securityQuestion;
	}

	public SecurityQuestions(int id, String securityQuestion) {
		this.id = id;
		this.securityQuestion = securityQuestion;
	}
	
	public SecurityQuestions(String securityQuestion, Set<SecChargeQuestions> secChargeQuestions) {
		this.securityQuestion = securityQuestion;
		this.secChargeQuestions = secChargeQuestions;
	}

	public SecurityQuestions(int id, String securityQuestion, Set<SecChargeQuestions> secChargeQuestions) {
		this(securityQuestion, secChargeQuestions);
		this.id = id;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, precision = 5, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "SECURITYQUESTION", nullable = false, length = 200)
	public String getSecurityQuestion() {
		return this.securityQuestion;
	}

	public void setSecurityQuestion(String securityQuestion) {
		this.securityQuestion = securityQuestion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "securityQuestions",cascade=CascadeType.ALL)
	public Set<SecChargeQuestions> getSecChargeQuestions() {
		return this.secChargeQuestions;
	}

	public void setSecChargeQuestions(Set<SecChargeQuestions> secChargeQuestions) {
		this.secChargeQuestions = secChargeQuestions;
	}

	@Override
	public String toString() {
		return "SecurityQuestions [id=" + id + ", securityQuestion=" + securityQuestion + ", secChargeQuestions="
				+ secChargeQuestions + "]";
	}
}
