package com.uottawa.seccharge.dataobjects;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SiteStatus generated by hbm2java
 */
@Entity
@Table(name = "SITE_STATUS")
public class SiteStatus implements Serializable {

	private long id;
	private ChargingStation chargingStation;
	private CsSite csSite;
	private long csId;
	private boolean enabled;
	private boolean occupied;

	public SiteStatus() {
	}

	public SiteStatus(ChargingStation chargingStation, CsSite csSite, long csId, boolean enabled, boolean occupied) {
		this.chargingStation = chargingStation;
		this.csSite = csSite;
		this.csId = csId;
		this.enabled = enabled;
		this.occupied = occupied;
	}

	public SiteStatus(long id, ChargingStation chargingStation, CsSite csSite, long csId, boolean enabled, boolean occupied) {
		this(chargingStation, csSite, csId, enabled, occupied);
		this.id = id;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CHARGING_STATIONID", nullable = false)
	public ChargingStation getChargingStation() {
		return this.chargingStation;
	}

	public void setChargingStation(ChargingStation chargingStation) {
		this.chargingStation = chargingStation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CS_SITEID", nullable = false)
	public CsSite getCsSite() {
		return this.csSite;
	}

	public void setCsSite(CsSite csSite) {
		this.csSite = csSite;
	}

	@Column(name = "CS_ID", nullable = false, precision = 10, scale = 0)
	public long getCsId() {
		return this.csId;
	}

	public void setCsId(long csId) {
		this.csId = csId;
	}

	@Column(name = "ENABLED", nullable = false, precision = 1, scale = 0)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@Column(name = "OCCUPIED", nullable = false, precision = 1, scale = 0)
	public boolean isOccupied() {
		return this.occupied;
	}

	public void setOccupied(boolean occupied) {
		this.occupied = occupied;
	}

	@Override
	public String toString() {
		return "SiteStatus [id=" + id + ", chargingStation=" + chargingStation + ", csSite=" + csSite + ", csId=" + csId
				+ ", enabled=" + enabled + ", occupied=" + occupied + "]";
	}

}
