package com.uottawa.seccharge.dataobjects;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SiteReservation generated by hbm2java
 */
@Entity
@Table(name = "SITE_RESERVATION")
public class SiteReservation implements Serializable {

	private SiteReservationId id;
	private Reservation reservation;
	private CsSite csSite;
	private Date startTime;
	private Date endTime;
	private Long csId;

	public SiteReservation() {
	}

	public SiteReservation(Reservation reservation, CsSite csSite, Date startTime,
			Date endTime) {
		this.reservation = reservation;
		this.csSite = csSite;
		this.startTime = startTime;
		this.endTime = endTime;
	}
	
	public SiteReservation(SiteReservationId id, Reservation reservation, CsSite csSite, 
			Date startTime,
			Date endTime) {
		this(reservation, csSite, startTime, endTime);
		this.id = id;
	}
	
	public SiteReservation(Reservation reservation, CsSite csSite, Date startTime,
			Date endTime, Long csId) {
		this.reservation = reservation;
		this.csSite = csSite;
		this.startTime = startTime;
		this.endTime = endTime;
		this.csId = csId;
	}

	public SiteReservation(SiteReservationId id, Reservation reservation, CsSite csSite, Date startTime,
			Date endTime, Long csId) {
		this(reservation, csSite, startTime, endTime, csId);
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false, precision = 32, scale = 0)),
			@AttributeOverride(name = "csSiteid", column = @Column(name = "CS_SITEID", nullable = false, precision = 32, scale = 0)),
			@AttributeOverride(name = "reservationid", column = @Column(name = "RESERVATIONID", nullable = false, precision = 32, scale = 0)) })
	public SiteReservationId getId() {
		return this.id;
	}

	public void setId(SiteReservationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RESERVATIONID", nullable = false, insertable = false, updatable = false)
	public Reservation getReservation() {
		return this.reservation;
	}

	public void setReservation(Reservation reservation) {
		this.reservation = reservation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CS_SITEID", nullable = false, insertable = false, updatable = false)
	public CsSite getCsSite() {
		return this.csSite;
	}

	public void setCsSite(CsSite csSite) {
		this.csSite = csSite;
	}

	@Column(name = "STARTTIME", nullable = false)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Column(name = "ENDTIME", nullable = false)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "CS_ID", precision = 10, scale = 0)
	public Long getCsId() {
		return this.csId;
	}

	public void setCsId(Long csId) {
		this.csId = csId;
	}

	@Override
	public String toString() {
		return "SiteReservation [id=" + id + ", reservation=" + reservation + ", csSite=" + csSite + ", startTime="
				+ startTime + ", endTime=" + endTime + ", csId=" + csId + "]";
	}

}
