package com.uottawa.seccharge.dataobjects;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ThirdprtyBilling generated by hbm2java
 */
@Entity
@Table(name = "THIRDPRTY_BILLING")
public class ThirdprtyBilling implements Serializable {

	private Long id;
	private SecChargeUser secChargeUser;
	private String accountNumber;
	private Date dateCreated;
	private boolean enabled;

	public ThirdprtyBilling() {
	}
	
	public ThirdprtyBilling(SecChargeUser secChargeUser, String accountNumber, Date dateCreated, boolean enabled) {
		this.secChargeUser = secChargeUser;
		this.accountNumber = accountNumber;
		this.dateCreated = dateCreated;
		this.enabled = enabled;
	}

	public ThirdprtyBilling(Long id, SecChargeUser secChargeUser, String accountNumber, Date dateCreated, boolean enabled) {
		this(secChargeUser, accountNumber, dateCreated, enabled);
		this.id = id;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, precision = 32, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SECCHARGE_USERID", nullable = false)
	public SecChargeUser getSecChargeUser() {
		return this.secChargeUser;
	}

	public void setSecChargeUser(SecChargeUser secChargeUser) {
		this.secChargeUser = secChargeUser;
	}

	@Column(name = "ACCOUNTNUMBER", nullable = false, length = 50)
	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATECREATED", nullable = false, length = 7)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "ENABLED", nullable = false, precision = 1, scale = 0)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@Override
	public String toString() {
		return "ThirdprtyBilling [id=" + id + ", secChargeUser=" + secChargeUser + ", accountNumber=" + accountNumber
				+ ", dateCreated=" + dateCreated + ", enabled=" + enabled + "]";
	}

}
