package com.uottawa.seccharge.dataobjects;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Transactions generated by hbm2java
 */
@Entity
@Table(name = "TRANSACTIONS")
public class Transactions implements Serializable {

	private Long id;
	private SecChargeUser secChargeUser;
	private String vehicleVin;
	private Serializable startTime;
	private Serializable endTime;
	private Serializable transactionDuration;
	private Set<EvCharging> evChargings = new HashSet<EvCharging>(0);
	private Set<TransactionHistroy> transactionHistroys = new HashSet<TransactionHistroy>(0);

	public Transactions() {
	}

	public Transactions(SecChargeUser secChargeUser, String vehicleVin, Serializable startTime, Serializable endTime,
			Serializable transactionDuration) {
		this.secChargeUser = secChargeUser;
		this.vehicleVin = vehicleVin;
		this.startTime = startTime;
		this.endTime = endTime;
		this.transactionDuration = transactionDuration;
	}

	public Transactions(Long id, SecChargeUser secChargeUser, String vehicleVin, Serializable startTime,
			Serializable endTime, Serializable transactionDuration) {
		this(secChargeUser, vehicleVin, startTime, endTime, transactionDuration);
		this.id = id;
	}

	public Transactions(SecChargeUser secChargeUser, String vehicleVin, Serializable startTime, Serializable endTime,
			Serializable transactionDuration, Set<EvCharging> evChargings, Set<TransactionHistroy> transactionHistroys) {
		this(secChargeUser, vehicleVin, startTime, endTime, transactionDuration);
		this.evChargings = evChargings;
		this.transactionHistroys = transactionHistroys;
	}

	public Transactions(Long id, SecChargeUser secChargeUser, String vehicleVin, Serializable startTime,
			Serializable endTime, Serializable transactionDuration, Set<EvCharging> evChargings,
			Set<TransactionHistroy> transactionHistroys) {
		this(secChargeUser, vehicleVin, startTime, endTime, transactionDuration, evChargings, transactionHistroys);
		this.id = id;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, precision = 32, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SECCHARGE_USERID", nullable = false)
	public SecChargeUser getSecChargeUser() {
		return this.secChargeUser;
	}

	public void setSecChargeUser(SecChargeUser secChargeUser) {
		this.secChargeUser = secChargeUser;
	}

	@Column(name = "VEHICLEVIN", nullable = false, length = 20)
	public String getVehicleVin() {
		return this.vehicleVin;
	}

	public void setVehicleVin(String vehicleVin) {
		this.vehicleVin = vehicleVin;
	}

	@Column(name = "STARTTIME", nullable = false)
	public Serializable getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Serializable startTime) {
		this.startTime = startTime;
	}

	@Column(name = "ENDTIME", nullable = false)
	public Serializable getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Serializable endTime) {
		this.endTime = endTime;
	}

	@Column(name = "TRANSACTIONDURATION", nullable = false)
	public Serializable getTransactionDuration() {
		return this.transactionDuration;
	}

	public void setTransactionDuration(Serializable transactionDuration) {
		this.transactionDuration = transactionDuration;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transactions",cascade=CascadeType.ALL)
	public Set<EvCharging> getEvChargings() {
		return this.evChargings;
	}

	public void setEvChargings(Set<EvCharging> evChargings) {
		this.evChargings = evChargings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transactions",cascade=CascadeType.ALL)
	public Set<TransactionHistroy> getTransactionHistroys() {
		return this.transactionHistroys;
	}

	public void setTransactionHistroys(Set<TransactionHistroy> transactionHistroys) {
		this.transactionHistroys = transactionHistroys;
	}

	@Override
	public String toString() {
		return "Transactions [id=" + id + ", secChargeUser=" + secChargeUser + ", vehicleVin=" + vehicleVin + ", startTime="
				+ startTime + ", endTime=" + endTime + ", transactionDuration=" + transactionDuration + ", evChargings="
				+ evChargings + ", transactionHistroys=" + transactionHistroys + "]";
	}

}
