package com.uottawa.seccharge.dataobjects;

import java.io.Serializable;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TransactionHistroy generated by hbm2java
 */
@Entity
@Table(name = "TRANSACTION_HISTROY")
public class TransactionHistroy implements Serializable {

	private TransactionHistroyId id;
	private Transactions transactions;
	private SecChargeUser secChargeUser;
	private Serializable chargingDuration;
	private Long consumptionKwh;

	public TransactionHistroy() {
	}
	
	public TransactionHistroy(Transactions transactions, SecChargeUser secChargeUser,
			Serializable chargingDuration, Long consumptionKwh) {
		this.transactions = transactions;
		this.secChargeUser = secChargeUser;
		this.chargingDuration = chargingDuration;
		this.consumptionKwh = consumptionKwh;
	}

	public TransactionHistroy(TransactionHistroyId id, Transactions transactions, SecChargeUser secChargeUser,
			Serializable chargingDuration, Long consumptionKwh) {
		this(transactions, secChargeUser, chargingDuration, consumptionKwh);
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false, precision = 32, scale = 0)),
			@AttributeOverride(name = "userMetadataid", column = @Column(name = "USER_METADATAID", nullable = false, precision = 32, scale = 0)) })
	public TransactionHistroyId getId() {
		return this.id;
	}

	public void setId(TransactionHistroyId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRANSACTIONID", nullable = false)
	public Transactions getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Transactions transactions) {
		this.transactions = transactions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SECCHARGE_USERID", nullable = false, insertable = false, updatable = false)
	public SecChargeUser getSecChargeUser() {
		return this.secChargeUser;
	}

	public void setSecChargeUser(SecChargeUser secChargeUser) {
		this.secChargeUser = secChargeUser;
	}

	@Column(name = "CHARGINGDURATION", nullable = false)
	public Serializable getChargingDuration() {
		return this.chargingDuration;
	}

	public void setChargingDuration(Serializable chargingDuration) {
		this.chargingDuration = chargingDuration;
	}

	@Column(name = "CONSUMPTIONKWH", nullable = false, precision = 10, scale = 10)
	public Long getConsumptionKwh() {
		return this.consumptionKwh;
	}

	public void setConsumptionKwh(Long consumptionKwh) {
		this.consumptionKwh = consumptionKwh;
	}

	@Override
	public String toString() {
		return "TransactionHistroy [id=" + id + ", transactions=" + transactions + ", secChargeUser=" + secChargeUser
				+ ", chargingDuration=" + chargingDuration + ", consumptionKwh=" + consumptionKwh + "]";
	}

}
