package com.uottawa.seccharge.dataobjects;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UserMetadata generated by hbm2java
 */
@Entity
@Table(name = "USER_METADATA", uniqueConstraints = @UniqueConstraint(columnNames = "EMAIL"))
public class UserMetadata implements Serializable {

	private Long id;
	private SecChargeUser secChargeUser;
	private String userSalt;
	private String firstName;
	private String lastName;
	private String companyName;
	private String email;
	private Date dateCreated;
	private Date expiryDate;
	private String address1;
	private String address2;
	private String city;
	private String province;
	private String postalCode;
	private String country;
	private String homePhone;
	private String cellPhone;
	private String fax;

	public UserMetadata() {
	}

	public UserMetadata(Long id, String userSalt, SecChargeUser secChargeUser, String firstName, String lastName,
			String email, Date dateCreated, String city, String province) {
		this(userSalt, secChargeUser, firstName, lastName, email, dateCreated, city, province);
		this.id = id;
	}

	public UserMetadata(String userSalt, SecChargeUser secChargeUser, String firstName, String lastName, String email,
			Date dateCreated, String city, String province) {
		this.userSalt = userSalt;
		this.secChargeUser = secChargeUser;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.dateCreated = dateCreated;
		this.city = city;
		this.province = province;
	}

	public UserMetadata(Long id, String userSalt, SecChargeUser secChargeUser, String firstName, String lastName,
			String companyName, String email, Date dateCreated, Date expiryDate, String address1, String address2,
			String city, String province, String postalCode, String country, String homePhone, String cellPhone, String fax) {
		this(userSalt, secChargeUser, firstName, lastName, companyName, email, dateCreated, expiryDate, address1, address2,
				city, province, postalCode, country, homePhone, cellPhone, fax);
		this.id = id;
	}

	public UserMetadata(String userSalt, SecChargeUser secChargeUser, String firstName, String lastName, String companyName,
			String email, Date dateCreated, Date expiryDate, String address1, String address2, String city, String province,
			String postalCode, String country, String homePhone, String cellPhone, String fax) {
		this(userSalt, firstName, lastName, companyName, email, dateCreated, expiryDate, address1, address2, city, province,
				postalCode, country, homePhone, cellPhone, fax);
		this.secChargeUser=secChargeUser;
	}

	public UserMetadata(String userSalt, String firstName, String lastName, String companyName, String email,
			Date dateCreated, Date expiryDate, String address1, String address2, String city, String province,
			String postalCode, String country, String homePhone, String cellPhone, String fax) {
		this.userSalt = userSalt;
		this.firstName = firstName;
		this.lastName = lastName;
		this.companyName = companyName;
		this.email = email;
		this.dateCreated = dateCreated;
		this.expiryDate = expiryDate;
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.province = province;
		this.postalCode = postalCode;
		this.country = country;
		this.homePhone = homePhone;
		this.cellPhone = cellPhone;
		this.fax = fax;
	}

	@Id
	@GeneratedValue
	@Column(name = "ID", unique = true, nullable = false, precision = 32, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "SECCHARGE_USERID", nullable = false)
	public SecChargeUser getSecChargeUser() {
		return this.secChargeUser;
	}

	public void setSecChargeUser(SecChargeUser secChargeUser) {
		this.secChargeUser = secChargeUser;
	}

	@Column(name = "USERSALT", unique = false, nullable = false, length = 80)
	public String getUserSalt() {
		return this.userSalt;
	}

	public void setUserSalt(String userSalt) {
		this.userSalt = userSalt;
	}

	@Column(name = "FIRSTNAME", nullable = false, length = 40)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LASTNAME", nullable = false, length = 40)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "COMPANYNAME")
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "EMAIL", unique = true, nullable = false, length = 40)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATECREATED", nullable = false, length = 7)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPIRYDATE", length = 7)
	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	@Column(name = "ADDRESS1")
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "ADDRESS2")
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "CITY", nullable = false, length = 40)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "PROVINCE", nullable = false, length = 40)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "POSTALCODE", length = 10)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "COUNTRY", length = 40)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "HOMEPHONE", length = 20)
	public String getHomePhone() {
		return this.homePhone;
	}

	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}

	@Column(name = "CELLPHONE", length = 20)
	public String getCellPhone() {
		return this.cellPhone;
	}

	public void setCellPhone(String cellPhone) {
		this.cellPhone = cellPhone;
	}

	@Column(name = "FAX", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Override
	public String toString() {
		// return "UserMetadata [id=" + id + ", secChargeUser=" + secChargeUser
		return "UserMetadata [id=" + id + ", userSalt=" + userSalt + ", firstName=" + firstName + ", lastName=" + lastName
				+ ", companyName=" + companyName + ", email=" + email + ", dateCreated=" + dateCreated + ", expiryDate="
				+ expiryDate + ", address1=" + address1 + ", address2=" + address2 + ", city=" + city + ", province="
				+ province + ", postalCode=" + postalCode + ", country=" + country + ", homePhone=" + homePhone
				+ ", cellPhone=" + cellPhone + ", fax=" + fax + "]";
	}

}
